name: Build and Test

on:
  pull_request:
    branches:
      - "*"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup build agent
        run: ./.github/scripts/setup.sh

      # echo "targets=$(pixlet community target-determinator --old ${GITHUB_BASE_REF} --new ${GITHUB_HEAD_REF})" >> $GITHUB_OUTPUT
      - name: Determine targets
        id: targets
        run: |
          git show-ref
          echo ${GITHUB_BASE_REF}
          echo ${GITHUB_HEAD_REF}
          pixlet community target-determinator --old refs/remotes/origin/${GITHUB_BASE_REF} --new ${GITHUB_SHA}

      - name: Check all apps
        run: pixlet check -r ${{steps.targets.output.targets}}

      - name: Sanity check go embed
        run: go test tidbyt.dev/community/apps
