name: Build and Test

on:
  pull_request:
    branches:
      - "*"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup build agent
        run: ./.github/scripts/setup.sh

      - name: Determine targets
        run: |
          echo ${GITHUB_BASE_REF}
          OLD_COMMIT=9ff13f79de921fba3bf9a10a0d47e978676d7ab9
          NEW_COMMIT=${GITHUB_SHA}
          echo ${OLD_COMMIT}
          echo ${NEW_COMMIT}
          pixlet community target-determinator --old ${OLD_COMMIT} --new ${NEW_COMMIT}

      - name: Check all apps
        run: pixlet check -r ./

      - name: Sanity check go embed
        run: go test tidbyt.dev/community/apps
